config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  resources :artists, only: [:index, :show]
 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Real Music</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span  class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Artistas", root_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Mi música</a>
      </li>
    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mr-2">
        <li class="nav-item dropdown align-right">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mi Cuenta
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Perfil</a>
          <a class="dropdown-item" href="#">Editar</a>
          <a class="dropdown-item" href="#">Salir</a>
        </div>
        </li>
      </ul>
    </div> 
    </ul>
  </div>
</nav>

app/views/artists/index.html.erb
<div class="container">
  <div class="row">
    <div class= "col-sm-12">
      <%= render 'navbar' %>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <% @artists.each do |artist| %>
        <div class="col-sm-3 pt-3">
          <div class="card">
            <img class="card-img-top p-1" src="<%= artist.image_url %>" alt="artistas">
            <div class="card-body">
              <h5 class="card-title text-center"><strong><%= artist.name %></strong></h5>
              <%= link_to "Ver más", artist_path(artist.id), class:"btn btn-primary btn-block"%>
            </div>
          </div>
        </div>
      <% end %>  
    </div>  
  </div>
</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="row">
    <div class= "col-sm-12">
      <%= render 'navbar' %>
    </div>
  </div>

  <div class="container">
    <div class="row">

      <div class="col-sm-7 ">
        <h3 class="mt-4"><strong><%=@artist.name%></strong></h3>
        <h5 class="mt-4"><strong>Albums (<%=@albums.count%>)</strong></h5>
        <div class="row">
          <%@albums.each do |album|%>
            <div class="col-sm-3 pt-3">
              <div class="card h-100">
                <img class="card-img-album p-1" id="album" src="<%= album.image_url %>" alt="albums">
                <div class="card-body p-2">
                  <h6 class="card-title text-center"><strong><%= album.name %></strong></h6>
                  <p class="card-text"><%=album.released_at%></p>
                </div>
              </div>
            </div>
          <% end %>  
        </div>
      </div>

      <div class="col-sm-1"></div>

      <div class="col-sm-4">
        <img src="<%=@artist.image_url%>" alt="artistas" class="rounded img-artist mt-4" >
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>